default:
  image: ocaml/opam2

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "[Building]"
    - opam pin ./
    - opam install eva_asm

test:
  stage: test
  script:
    - echo "[Testing]"
    - dune runtest
  
