default:
  image: ocaml/opam

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "[Building]"
    - opam install .

test:
  stage: test
  script:
    - echo "[Testing]"
    - dune runtest
  
