default:
  image: ocaml/opam2:4.07
  before_script:
    - opam init
    - eval `opam config env`
    - sudo apt-get -y install m4 make patch libc-dev gcc

stages:
  - build
  - test

build:
  stage: build
  script:
    - opam pin ./
    - opam install eva_asm

test:
  stage: test
  script:
    - dune runtest
  
