default:
  image: ocaml/opam2:4.07
  before_script:
    - opam init
    - eval `opam config env`
<<<<<<< HEAD
=======
    - opam install m4
>>>>>>> 920901796f9bd33bbe2248652d4b665370863e5e

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "[Building]"
    - opam pin ./
    - opam install eva_asm

test:
  stage: test
  script:
    - echo "[Testing]"
    - dune runtest
  
