default:
  image: ocaml/opam2:4.07
  before_script:
    - opam init
    - eval `opam config env`
    - opam install m4

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "[Building]"
    - opam pin ./
    - opam install eva_asm

test:
  stage: test
  script:
    - echo "[Testing]"
    - dune runtest
  
